// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingServiceClient interface {
	// CreateSubscriptionCheckout initiates a Stripe subscription checkout session
	CreateSubscriptionCheckout(ctx context.Context, in *CreateSubscriptionCheckoutRequest, opts ...grpc.CallOption) (*CreateSubscriptionCheckoutResponse, error)
	// GetSubscriptionStatus retrieves the current status of a user's subscription
	GetSubscriptionStatus(ctx context.Context, in *GetSubscriptionStatusRequest, opts ...grpc.CallOption) (*GetSubscriptionStatusResponse, error)
	// CreateCustomerPortal creates a Stripe customer portal session for subscription management
	CreateCustomerPortal(ctx context.Context, in *CreateCustomerPortalRequest, opts ...grpc.CallOption) (*CreateCustomerPortalResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) CreateSubscriptionCheckout(ctx context.Context, in *CreateSubscriptionCheckoutRequest, opts ...grpc.CallOption) (*CreateSubscriptionCheckoutResponse, error) {
	out := new(CreateSubscriptionCheckoutResponse)
	err := c.cc.Invoke(ctx, "/billing.BillingService/CreateSubscriptionCheckout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetSubscriptionStatus(ctx context.Context, in *GetSubscriptionStatusRequest, opts ...grpc.CallOption) (*GetSubscriptionStatusResponse, error) {
	out := new(GetSubscriptionStatusResponse)
	err := c.cc.Invoke(ctx, "/billing.BillingService/GetSubscriptionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CreateCustomerPortal(ctx context.Context, in *CreateCustomerPortalRequest, opts ...grpc.CallOption) (*CreateCustomerPortalResponse, error) {
	out := new(CreateCustomerPortalResponse)
	err := c.cc.Invoke(ctx, "/billing.BillingService/CreateCustomerPortal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility
type BillingServiceServer interface {
	// CreateSubscriptionCheckout initiates a Stripe subscription checkout session
	CreateSubscriptionCheckout(context.Context, *CreateSubscriptionCheckoutRequest) (*CreateSubscriptionCheckoutResponse, error)
	// GetSubscriptionStatus retrieves the current status of a user's subscription
	GetSubscriptionStatus(context.Context, *GetSubscriptionStatusRequest) (*GetSubscriptionStatusResponse, error)
	// CreateCustomerPortal creates a Stripe customer portal session for subscription management
	CreateCustomerPortal(context.Context, *CreateCustomerPortalRequest) (*CreateCustomerPortalResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBillingServiceServer struct {
}

func (UnimplementedBillingServiceServer) CreateSubscriptionCheckout(context.Context, *CreateSubscriptionCheckoutRequest) (*CreateSubscriptionCheckoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscriptionCheckout not implemented")
}
func (UnimplementedBillingServiceServer) GetSubscriptionStatus(context.Context, *GetSubscriptionStatusRequest) (*GetSubscriptionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptionStatus not implemented")
}
func (UnimplementedBillingServiceServer) CreateCustomerPortal(context.Context, *CreateCustomerPortalRequest) (*CreateCustomerPortalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomerPortal not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_CreateSubscriptionCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateSubscriptionCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.BillingService/CreateSubscriptionCheckout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateSubscriptionCheckout(ctx, req.(*CreateSubscriptionCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetSubscriptionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetSubscriptionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.BillingService/GetSubscriptionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetSubscriptionStatus(ctx, req.(*GetSubscriptionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CreateCustomerPortal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerPortalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateCustomerPortal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.BillingService/CreateCustomerPortal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateCustomerPortal(ctx, req.(*CreateCustomerPortalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSubscriptionCheckout",
			Handler:    _BillingService_CreateSubscriptionCheckout_Handler,
		},
		{
			MethodName: "GetSubscriptionStatus",
			Handler:    _BillingService_GetSubscriptionStatus_Handler,
		},
		{
			MethodName: "CreateCustomerPortal",
			Handler:    _BillingService_CreateCustomerPortal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/billing.proto",
}
